back_end/config/routes.rb
Rails.application.routes.draw do
  resources :update_views
  resources :user_profiles
  # resources :myprofiles
  resources :group_version_numbers
  resources :groups
  resources :user_matches
  resources :user_preferences
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :room_messages
  resources :rooms
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :myprofiles
  get "myprofile" => "yours#profile", :as => :myprofile

  root controller: :rooms, action: :index
end

back_end/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

back_end/app/models/gro.rb
class Gro < ApplicationRecord
end

back_end/app/models/group.rb
class Group < ApplicationRecord
end

back_end/app/models/group_version_number.rb
class GroupVersionNumber < ApplicationRecord
end

back_end/app/models/match_reports.rb
class MatchReports < ActiveRecord::Base
    def self.refresh
      Scenic
        .database
        .refresh_materialized_view(table_name, concurrently: false)
    end
  
    def readonly?
      true
    end
  end

back_end/app/models/myprofile.rb
class Myprofile < ApplicationRecord
end

back_end/app/models/room.rb
class Room < ApplicationRecord
    has_many :room_messages, dependent: :destroy, inverse_of: :room
end

back_end/app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :room, inverse_of: :room_messages
  belongs_to :user

  def as_json(options)
    super(options).merge(user_avatar_url: user.gravatar_url)
  end
end

back_end/app/models/update_view.rb
class UpdateView < ApplicationRecord
end

back_end/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :username, uniqueness: true, presence: true

  def gravatar_url
    gravatar_id = Digest::MD5::hexdigest(email).downcase
    "https://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

back_end/app/models/user_match.rb
class UserMatch < ApplicationRecord
end

back_end/app/models/user_preference.rb
class UserPreference < ApplicationRecord
end

back_end/app/models/user_profile.rb
class UserProfile < ApplicationRecord
end

back_end/app/controllers/gros_controller.rb
class GrosController < ApplicationController
  before_action :set_gro, only: [:show, :edit, :update, :destroy]

  # GET /gros
  # GET /gros.json
  def index
    @gros = Gro.all
  end

  # GET /gros/1
  # GET /gros/1.json
  def show
  end

  # GET /gros/new
  def new
    @gro = Gro.new
  end

  # GET /gros/1/edit
  def edit
  end

  # POST /gros
  # POST /gros.json
  def create
    @gro = Gro.new(gro_params)

    respond_to do |format|
      if @gro.save
        format.html { redirect_to @gro, notice: 'Gro was successfully created.' }
        format.json { render :show, status: :created, location: @gro }
      else
        format.html { render :new }
        format.json { render json: @gro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gros/1
  # PATCH/PUT /gros/1.json
  def update
    respond_to do |format|
      if @gro.update(gro_params)
        format.html { redirect_to @gro, notice: 'Gro was successfully updated.' }
        format.json { render :show, status: :ok, location: @gro }
      else
        format.html { render :edit }
        format.json { render json: @gro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gros/1
  # DELETE /gros/1.json
  def destroy
    @gro.destroy
    respond_to do |format|
      format.html { redirect_to gros_url, notice: 'Gro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gro
      @gro = Gro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gro_params
      params.require(:gro).permit(:version)
    end
end

back_end/app/controllers/group_version_numbers_controller.rb
class GroupVersionNumbersController < ApplicationController
  before_action :set_group_version_number, only: [:show, :edit, :update, :destroy]

  # GET /group_version_numbers
  # GET /group_version_numbers.json
  def index
    @group_version_numbers = GroupVersionNumber.all
  end

  # GET /group_version_numbers/1
  # GET /group_version_numbers/1.json
  def show
  end

  # GET /group_version_numbers/new
  def new
    @group_version_number = GroupVersionNumber.new
  end

  # GET /group_version_numbers/1/edit
  def edit
  end

  # POST /group_version_numbers
  # POST /group_version_numbers.json
  def create
    @group_version_number = GroupVersionNumber.new(group_version_number_params)

    respond_to do |format|
      if @group_version_number.save
        format.html { redirect_to @group_version_number, notice: 'Group version number was successfully created.' }
        format.json { render :show, status: :created, location: @group_version_number }
      else
        format.html { render :new }
        format.json { render json: @group_version_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_version_numbers/1
  # PATCH/PUT /group_version_numbers/1.json
  def update
    respond_to do |format|
      if @group_version_number.update(group_version_number_params)
        format.html { redirect_to @group_version_number, notice: 'Group version number was successfully updated.' }
        format.json { render :show, status: :ok, location: @group_version_number }
      else
        format.html { render :edit }
        format.json { render json: @group_version_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_version_numbers/1
  # DELETE /group_version_numbers/1.json
  def destroy
    @group_version_number.destroy
    respond_to do |format|
      format.html { redirect_to group_version_numbers_url, notice: 'Group version number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_version_number
      @group_version_number = GroupVersionNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_version_number_params
      params.require(:group_version_number).permit(:version)
    end
end

back_end/app/helpers/application_helper.rb
module ApplicationHelper
end

back_end/app/helpers/gros_helper.rb
module GrosHelper
end

back_end/app/helpers/group_version_numbers_helper.rb
module GroupVersionNumbersHelper
end

back_end/app/helpers/groups_helper.rb
module GroupsHelper
end

back_end/app/helpers/myprofiles_helper.rb
module MyprofilesHelper
end

back_end/app/helpers/rooms_helper.rb
module RoomsHelper
end

back_end/app/helpers/update_views_helper.rb
module UpdateViewsHelper
end

back_end/app/helpers/user_matches_helper.rb
module UserMatchesHelper
end

back_end/app/views/group_version_numbers/_form.html.erb
<%= form_with(model: group_version_number, local: true) do |form| %>
  <% if group_version_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group_version_number.errors.count, "error") %> prohibited this group_version_number from being saved:</h2>

      <ul>
        <% group_version_number.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :version %>
    <%= form.number_field :version %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

back_end/app/views/group_version_numbers/edit.html.erb
<h1>Editing Group Version Number</h1>

<%= render 'form', group_version_number: @group_version_number %>

<%= link_to 'Show', @group_version_number %> |
<%= link_to 'Back', group_version_numbers_path %>

back_end/app/views/group_version_numbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Group Version Numbers</h1>

<table>
  <thead>
    <tr>
      <th>Version</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @group_version_numbers.each do |group_version_number| %>
      <tr>
        <td><%= group_version_number.version %></td>
        <td><%= link_to 'Show', group_version_number %></td>
        <td><%= link_to 'Edit', edit_group_version_number_path(group_version_number) %></td>
        <td><%= link_to 'Destroy', group_version_number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group Version Number', new_group_version_number_path %>

back_end/app/views/group_version_numbers/new.html.erb
<h1>New Group Version Number</h1>

<%= render 'form', group_version_number: @group_version_number %>

<%= link_to 'Back', group_version_numbers_path %>

back_end/app/views/group_version_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Version:</strong>
  <%= @group_version_number.version %>
</p>

<%= link_to 'Edit', edit_group_version_number_path(@group_version_number) %> |
<%= link_to 'Back', group_version_numbers_path %>