back_end/config/routes.rb
Rails.application.routes.draw do
  resources :update_views
  resources :user_profiles
  # resources :myprofiles
  resources :group_version_numbers
  resources :groups
  resources :user_matches
  resources :user_preferences
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :room_messages
  resources :rooms
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :myprofiles
  get "myprofile" => "yours#profile", :as => :myprofile

  root controller: :rooms, action: :index
end

back_end/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

back_end/app/models/gro.rb
class Gro < ApplicationRecord
end

back_end/app/models/group.rb
class Group < ApplicationRecord
end

back_end/app/models/group_version_number.rb
class GroupVersionNumber < ApplicationRecord
end

back_end/app/models/match_reports.rb
class MatchReports < ActiveRecord::Base
    def self.refresh
      Scenic
        .database
        .refresh_materialized_view(table_name, concurrently: false)
    end
  
    def readonly?
      true
    end
  end

back_end/app/models/myprofile.rb
class Myprofile < ApplicationRecord
end

back_end/app/models/room.rb
class Room < ApplicationRecord
    has_many :room_messages, dependent: :destroy, inverse_of: :room
end

back_end/app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :room, inverse_of: :room_messages
  belongs_to :user

  def as_json(options)
    super(options).merge(user_avatar_url: user.gravatar_url)
  end
end

back_end/app/models/update_view.rb
class UpdateView < ApplicationRecord
end

back_end/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :username, uniqueness: true, presence: true

  def gravatar_url
    gravatar_id = Digest::MD5::hexdigest(email).downcase
    "https://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

back_end/app/models/user_match.rb
class UserMatch < ApplicationRecord
end

back_end/app/models/user_preference.rb
class UserPreference < ApplicationRecord
end

back_end/app/models/user_profile.rb
class UserProfile < ApplicationRecord
end

back_end/app/controllers/gros_controller.rb
class GrosController < ApplicationController
  before_action :set_gro, only: [:show, :edit, :update, :destroy]

  # GET /gros
  # GET /gros.json
  def index
    @gros = Gro.all
  end

  # GET /gros/1
  # GET /gros/1.json
  def show
  end

  # GET /gros/new
  def new
    @gro = Gro.new
  end

  # GET /gros/1/edit
  def edit
  end

  # POST /gros
  # POST /gros.json
  def create
    @gro = Gro.new(gro_params)

    respond_to do |format|
      if @gro.save
        format.html { redirect_to @gro, notice: 'Gro was successfully created.' }
        format.json { render :show, status: :created, location: @gro }
      else
        format.html { render :new }
        format.json { render json: @gro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gros/1
  # PATCH/PUT /gros/1.json
  def update
    respond_to do |format|
      if @gro.update(gro_params)
        format.html { redirect_to @gro, notice: 'Gro was successfully updated.' }
        format.json { render :show, status: :ok, location: @gro }
      else
        format.html { render :edit }
        format.json { render json: @gro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gros/1
  # DELETE /gros/1.json
  def destroy
    @gro.destroy
    respond_to do |format|
      format.html { redirect_to gros_url, notice: 'Gro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gro
      @gro = Gro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gro_params
      params.require(:gro).permit(:version)
    end
end

back_end/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    # Loads:
    # @rooms = all rooms
    # @room = current room when applicable
    before_action :load_entities

    def execute_sql(sql)
      results = ActiveRecord::Base.connection.execute(sql)
      results.each do |res|
        puts res
      end
      return results
    end

    def get_rooms
      room_names=execute_sql("select CONCAT(interest,'.',version,'.', group_number)
                                FROM groups
                                WHERE
                                person='#{current_user.username}'
                                AND
                                version in (SELECT version from group_version_numbers order by version DESC limit 1)
").to_a
      puts room_names
      room_names_=[]
      room_names.each do |name|
        room_names_.push(name["concat"])
      end
      @rooms = Room.where(name: room_names_)
    end


    def get_members
      @room_members=execute_sql("select DISTINCT person
                                FROM groups JOIN
                                rooms ON
                                CONCAT(interest,'.',version,'.', group_number)=rooms.name
                                AND rooms.id=#{params[:id]}"
                                ).to_a
      # puts @room_members
    end

    def index
      get_rooms
    end
  
    def new
      @room = Room.new
    end
  
    def create
      @room = Room.new permitted_parameters
      puts permitted_parameters
      if @room.save
        flash[:success] = "Room #{@room.name} was created successfully"
        redirect_to rooms_path
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @room.update_attributes(permitted_parameters)
        flash[:success] = "Room #{@room.name} was updated successfully"
        redirect_to rooms_path
      else
        render :new
      end
    end
  
	def show
		@room_message = RoomMessage.new room: @room
		@room_messages = @room.room_messages.includes(:user)
	end
	
    protected
  
    def load_entities
      get_rooms
      @room = Room.find(params[:id]) if params[:id]
      get_members if params[:id]
    end
  
    def permitted_parameters
      params.require(:room).permit(:name)
    end
end

back_end/app/controllers/yours_controller.rb
class YoursController < ApplicationController

  def execute_sql(sql)
    results = ActiveRecord::Base.connection.execute(sql)
    results.each do |res|
      puts res
    end
    return results
  end

    def profile
      # cache.fetch("foo", force: true, raw: true) do
      #   :bar
      # end
      @account = current_user
      execute_sql("create extension IF NOT EXISTS fuzzystrmatch;")
      execute_sql("create extension IF NOT EXISTS pg_trgm;")
      
    memcahce_key= current_user.username+"_profile_cache"
    if Rails.cache.fetch(memcahce_key).nil?
        @preferences=execute_sql("SELECT up.interest,
          (SELECT COUNT(*)
            FROM user_preferences up1
             WHERE up.interest=up1.interest AND name!='#{current_user.username}')
          AS number_of_people_interested
    FROM user_preferences up
    WHERE name= '#{current_user.username}'
    ORDER BY number_of_people_interested DESC").to_a
    Rails.cache.write(memcahce_key, @preferences, expires_in: 5.minute)
    else
      @preferences=Rails.cache.fetch(memcahce_key)
      @cached="te"
    end
    end
   end

back_end/app/helpers/application_helper.rb
module ApplicationHelper
end

back_end/app/helpers/gros_helper.rb
module GrosHelper
end

back_end/app/helpers/groups_helper.rb
module GroupsHelper
end

back_end/app/helpers/myprofiles_helper.rb
module MyprofilesHelper
end

back_end/app/helpers/rooms_helper.rb
module RoomsHelper
end

back_end/app/helpers/update_views_helper.rb
module UpdateViewsHelper
end

back_end/app/helpers/user_matches_helper.rb
module UserMatchesHelper
end

back_end/app/views/gros/_form.html.erb
<%= form_with(model: gro, local: true) do |form| %>
  <% if gro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gro.errors.count, "error") %> prohibited this gro from being saved:</h2>

      <ul>
        <% gro.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :version %>
    <%= form.number_field :version %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

back_end/app/views/gros/edit.html.erb
<h1>Editing Gro</h1>

<%= render 'form', gro: @gro %>

<%= link_to 'Show', @gro %> |
<%= link_to 'Back', gros_path %>

back_end/app/views/gros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gros</h1>

<table>
  <thead>
    <tr>
      <th>Version</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gros.each do |gro| %>
      <tr>
        <td><%= gro.version %></td>
        <td><%= link_to 'Show', gro %></td>
        <td><%= link_to 'Edit', edit_gro_path(gro) %></td>
        <td><%= link_to 'Destroy', gro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gro', new_gro_path %>

back_end/app/views/gros/new.html.erb
<h1>New Gro</h1>

<%= render 'form', gro: @gro %>

<%= link_to 'Back', gros_path %>

back_end/app/views/gros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Version:</strong>
  <%= @gro.version %>
</p>

<%= link_to 'Edit', edit_gro_path(@gro) %> |
<%= link_to 'Back', gros_path %>

back_end/app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>
  <%= form.input :name %>
  <%= form.submit "Save", class: 'btn btn-success' %>
<% end %>

back_end/app/views/rooms/_rooms.html.erb
<% if @rooms.present? %>
  <% @rooms.each do |room| %>
  <label>
    <span>Room number is: <%= room.id %></span>
  </label>
  <% end %>
  <nav class="nav flex-column">
    <% @rooms.each do |room| %>
      <%= link_to room.name, room_path(room), class: 'nav-link room-nav-link' %>
    <% end %>
  </nav>
<% else %>
  <div class="text-muted">
    There are no groups yet :P
  </div>
<% end %>

back_end/app/views/rooms/edit.html.erb
<h1>
  Editing room <%= @room.name %>
</h1>

<%= render partial: 'form' %>

back_end/app/views/rooms/index.html.erb
<h1>Groups</h1>
<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
      <h4 class="alert-heading">
       We create groups of 6 random people based on your interests every week!
      </h4>
      <% if @rooms.present? %>
      <p>
        The rooms show up on the left side bar, happy chattting arkadash ;)
      </p>
        <% else %>
        <p>
        The rooms show up on the left side bar, seems like you dont have any groups yet :O
        but no worries we will find poeple for you very soon ;)
        Keep <a href="/user_preferences/new"><b>adding interests</b></a> to increase your chances Arkadash!
      </p>
      <% end %>
      <hr />

  </div>
</div>

back_end/app/views/rooms/new.html.erb
<h1>
  Creating a room  
</h1>

<%= render partial: 'form' %>

back_end/app/views/rooms/show.html.erb
<h1>
  <%= @room.name %>
</h1>

<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

  <div class="col">
    <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
      <% @room_messages.each do |room_message| %>
        <div class="chat-message-container">
          <div class="row no-gutters">
            <div class="col-auto text-center">
              <img src="<%= room_message.user.gravatar_url %>" class="avatar" alt="">
            </div>

            <div class="col">
              <div class="message-content">
                <p class="mb-1">
                  <%= room_message.message %>
                </p>

                <div class="text-right">
                  <small>
                    <%= room_message.created_at %>
                  </small>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <%= simple_form_for @room_message, remote: true do |form| %>
      <div class="input-group mb-3">
        <%= form.input :message, as: :string,
                                 wrapper: false,
                                 label: false,
                                 input_html: {
                                   class: 'chat-input'
                                 } %>
        <div class="input-group-append">
          <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
        </div>
      </div>

      <%= form.input :room_id, as: :hidden %>
    <% end %>
  </div>
</div>

<div class="d-none" data-role="message-template">
  <div class="chat-message-container">
    <div class="row no-gutters">
      <div class="col-auto text-center">
        <img src="" class="avatar" alt="" data-role="user-avatar">
      </div>

      <div class="col">
        <div class="message-content">
          <p class="mb-1" data-role="message-text"></p>

          <div class="text-right">
            <small data-role="message-date"></small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<h2>Members</h2>
<table>
  <tbody>
  <% @room_members.each do |member| %>
    <tr>
      <td><%= member['person'] %></td>
    </tr>
  <% end %>
  </tbody>
</table>